### ISSUE TITLE
Fix flaky test io.mantisrx.master.api.akka.route.v1.ResourceClusterNonLeaderRedirectRouteTest::testDisableTaskExecutorsRoute

### ISSUE THREAD

**Issue by liuml07** [Netflix/mantis#399]
Seems like the test is broken when running locally. Let's fix or improve it.

```
java.lang.AssertionError: Unexpected status code! expected:<200 OK> but was:<500 Internal Server Error>
  Request was:      HttpRequest(HttpMethod(POST),/api/v1/resourceClusters/myCluster/disableTaskExecutors,List(),HttpEntity.Strict(application/json,81 bytes total),HttpProtocol(HTTP/1.1))
  Route result was: FulfilledFuture(Complete(HttpResponse(500 Internal Server Error,List(Access-Control-Allow-Origin: *),HttpEntity.Strict(text/plain; charset=UTF-8,141 bytes total),HttpProtocol(HTTP/1.1))))

	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.reportDetails(JUnitRouteTest.scala:48)
	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.assertEquals(JUnitRouteTest.scala:31)
	at akka.http.javadsl.testkit.TestRouteResult.assertEqualsKind(TestRouteResult.scala:227)
	at akka.http.javadsl.testkit.TestRouteResult.assertStatusCode(TestRouteResult.scala:136)
	at akka.http.javadsl.testkit.TestRouteResult.assertStatusCode(TestRouteResult.scala:130)
	at io.mantisrx.master.api.akka.route.v1.ResourceClusterNonLeaderRedirectRouteTest.testDisableTaskExecutorsRoute(ResourceClusterNonLeaderRedirectRouteTest.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.AssertionError: Unexpected status code! expected:<200 OK> but was:<500 Internal Server Error>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.$anonfun$assertEquals$1(JUnitRouteTest.scala:31)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.reportDetails(JUnitRouteTest.scala:45)
	... 48 more
```

**Comment by vedant-pandey** [comment]
Hi, can I pick this issue up?

**Comment by nick2432** [comment]
can i work on this?

**Comment by ANIONite** [comment]
Hi, may I work on this?

**Comment by divyankshah** [comment]
This was already seems to be fixed, 4 months after it was filed.

Cause. The 500 is text/plain, which is Akka's default exception handler, not withFuture's error path (that one uses Jackson.marshaller(), so application/json). It's an unmatched Mockito stub: disableTaskExecutorsFor(...) returns null and onComplete(null) NPEs.

The expiry matcher was the problem. #367 (63c41cc, nine days before this issue) made the route compute Instant.now().plus(Duration.ofHours(19)) and stubbed it as:


expiry.isAfter (Instant.now().plus(Duration.ofHours(18))) &&
expiry.isBefore(Instant.now().plus(Duration.ofHours(19)))
The upper bound is exactly the value under test, so isBefore reduces to T_route < T_matcher. It only passes if the clock ticks between the route's Instant.now() and the matcher's. The stack trace here is Java 8, where Instant.now() has millisecond resolution, so both calls land in the same millisecond and it fails. On a JDK with a finer clock it passes, which is why this reproduced locally but not in CI.

Fix. 824c50d (#496, 2023-07-28) widened the window to 17h to 20h. It didn't reference this issue, so this stayed open.

Verified on current main (JDK 17, Gradle 8.11): test class passes standalone, full mantis-control-plane-server suite passes (384 tests, 0 failures), 20 consecutive runs of the class all pass.

Suggest closing. @liuml07
